### ISSUE TITLE
Rename when only (upper/lower) case changes

### ISSUE THREAD

**Issue by whyboris** [whyboris/Simplest-File-Renamer#23]
When renaming file only has case change (e.g. `ABC` to `abc`) the app fails to rename the file :trollface: 

Would be great to fix this bug 😅

**Comment by shravan-kaushik** [comment]
@whyboris I just encountered this issue. It's an easy fix, but I can't seem to get `npm i` to finish. It throws a bunch of errors. <details><summary>It looks like a version incompatibility issue.</summary>

<p>

```
_this = _super.call(this, input.message || input) || this                                                                                                                                                                     
^                                                                                                                                                                                                                            
Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.                                                                                                                                     
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:317:21)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.                                                                                                                                    
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:327:19)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.                                    
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:301:25)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.     
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:301:25)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environmen
t.                                                                                                                                                                                                                                            
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:301:25)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.          
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:301:25)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.               
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:301:25)                                                                                                
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.                                                                                      
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at isCompatibleEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:252:19)                                                                                             
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:287:4)                                                                                                 
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment                                                                                                                                   
    at new Errlop (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\errlop\edition-es5\index.js:61:18)                                                                                                         
    at Object.errtion (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\util.js:23:14)                                                                                                    
    at isCompatibleEngines (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:183:19)                                                                                             
    at isCompatibleEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:250:10)                                                                                             
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:287:4)                                                                                                 
    at determineEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:312:12)                                                                                                
    at solicitEdition (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:350:16)                                                                                                  
    at Object.requirePackage (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\editions\edition-es5\index.js:364:9)                                                                                            
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\istextorbinary\index.cjs:4:38)                                                                                                     
    at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                                                                                                                                             
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                                                                                                                                               
    at Module.load (node:internal/modules/cjs/loader:988:32)                                                                                                                                                                                  
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                                                                                                                                        
    at Module.require (node:internal/modules/cjs/loader:1012:19)                                                                                                                                                                              
    at require (node:internal/modules/cjs/helpers:93:18)                                                                                                                                                                                      
    at Object.<anonymous> (C:\Users\Shravan\AppData\Roaming\npm\node_modules\electron-builder\node_modules\app-builder-lib\electron-osx-sign\util.js:135:22)                                                                                  
```

</p>
</details>

Can you document the build steps?

**Comment by whyboris** [comment]
Weird - unsure what's happening here. It worked on my machine ™️  :trollface: (I have Windows as well)

Perhaps delete `package-lock.json` as well as the whole `node_modules` folder and try again 🤞 😓 🤞 

If it doesn't work I'll try a clean install on my PC to see if I can replicate what you encountered 🤝

**Comment by whyboris** [comment]
Related _Issue_ #79 and a possible _PR_ to fix it #25

**Comment by whyboris** [comment]
I'm eager to release version `2.0.0` which is built with _Tauri_ and is only about 3mb 🚀 

I'm postponing fixing this issue until a subsequent release 🤝

**Comment by whyboris** [comment]
Since this is a _duplicate_ issue, I'm closing it in favor of the more-recent #79 🤝
